# Generated by Django 3.2 on 2022-04-03 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='type',
            new_name='type_user',
        ),
    ]
