# Generated by Django 3.2 on 2022-04-03 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taked', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required and unique', max_length=255, unique=True, verbose_name='Nombre de la empresa')),
                ('razon_social', models.CharField(help_text='Required and unique', max_length=255, unique=True, verbose_name='Nombre de la empresa')),
                ('nit', models.CharField(help_text='Required and unique', max_length=255, unique=True, verbose_name='NIT')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_l', models.ImageField(max_length=255, null=True, upload_to='x/x1', verbose_name='picture size large 1024x1024')),
                ('img_m', models.ImageField(default='', max_length=255, null=True, upload_to='x/x5', verbose_name='picture size medium 400x400')),
                ('thumbnail', models.ImageField(default='', max_length=255, null=True, upload_to='x/x4', verbose_name='picture size small 70x70')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=512)),
                ('address', models.TextField(max_length=2048)),
                ('gps', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_l', models.ImageField(max_length=255, null=True, upload_to='x/x1', verbose_name='picture size large 1024x1024')),
                ('img_m', models.ImageField(default='', max_length=255, null=True, upload_to='x/x5', verbose_name='picture size medium 400x400')),
                ('thumbnail', models.ImageField(default='', max_length=255, null=True, upload_to='x/x4', verbose_name='picture size small 70x70')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=4096)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='travel.company')),
                ('destination', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_destination', to='travel.place')),
                ('origin', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_origin', to='travel.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_departure', models.DateTimeField()),
                ('time_arrival_destination', models.DateTimeField()),
                ('time_departure_return', models.DateTimeField(default=None, null=True)),
                ('time_arrival_return', models.DateTimeField(default=None, null=True)),
                ('travel_type', models.CharField(choices=[('I', 'Solo ida'), ('V', 'Ida y vuelta')], max_length=1)),
                ('available_seats', models.PositiveSmallIntegerField(default=1)),
                ('passengers_limit', models.PositiveIntegerField(default=0, help_text='If travel is limited, this will be the limit on the number of members.')),
                ('verified', models.BooleanField(default=False, help_text='Verified circles are also known as official communities.', verbose_name='verified circle')),
                ('rating', models.FloatField(null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Used for disabling the ride or marking it as finished.', verbose_name='active status')),
                ('bookers', models.ManyToManyField(related_name='travel_reserved', through='travel.Booker', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.service')),
            ],
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travel')),
            ],
        ),
        migrations.AddField(
            model_name='travel',
            name='travelers',
            field=models.ManyToManyField(related_name='travel_registered', through='travel.Traveler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booker',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travel'),
        ),
    ]
