# Generated by Django 3.2 on 2022-04-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='razon_social',
            field=models.CharField(help_text='Required and unique', max_length=255, verbose_name='Nombre de la empresa'),
        ),
    ]
