# Generated by Django 3.2 on 2022-04-10 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_company_razon_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='gps',
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travel',
            name='travel_type',
            field=models.CharField(choices=[('V', 'Ida y vuelta'), ('I', 'Solo ida')], max_length=1),
        ),
    ]
